"""Add ISBN to books

Revision ID: 457b9205d425
Revises: 1eb4581ecd2e
Create Date: 2025-05-28 20:28:48.477532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '457b9205d425'
down_revision: Union[str, None] = '1eb4581ecd2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('isbn', sa.String(), nullable=True))
    op.add_column('books', sa.Column('description', sa.String(), nullable=True))
    op.create_index(op.f('ix_books_isbn'), 'books', ['isbn'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_isbn'), table_name='books')
    op.drop_column('books', 'description')
    op.drop_column('books', 'isbn')
    # ### end Alembic commands ###
