"""Add weighted rating to books with index

Revision ID: b6a67ec01e7f
Revises: a2ea5969cc97
Create Date: 2025-09-15 19:45:57.043223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6a67ec01e7f'
down_revision: Union[str, None] = 'a2ea5969cc97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('global_weighted_love_rating', sa.Float(), nullable=True))
    op.add_column('books', sa.Column('global_weighted_shit_rating', sa.Float(), nullable=True))
    op.create_index(op.f('ix_books_global_weighted_love_rating'), 'books', ['global_weighted_love_rating'], unique=False)
    op.create_index(op.f('ix_books_global_weighted_shit_rating'), 'books', ['global_weighted_shit_rating'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_global_weighted_rating'), table_name='books')
    op.drop_column('books', 'global_weighted_rating')
    # ### end Alembic commands ###
