"""Add global rating stats table

Revision ID: a2ea5969cc97
Revises: 55d6c94f59ff
Create Date: 2025-09-14 17:52:40.268013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2ea5969cc97'
down_revision: Union[str, None] = '55d6c94f59ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_rating_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num_love_ratings', sa.Integer(), nullable=False),
    sa.Column('sum_love_ratings', sa.Float(), nullable=False),
    sa.Column('mean_love_rating', sa.Float(), nullable=False),
    sa.Column('num_shit_ratings', sa.Integer(), nullable=False),
    sa.Column('sum_shit_ratings', sa.Float(), nullable=False),
    sa.Column('mean_shit_rating', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('global_rating_stats')
    # ### end Alembic commands ###
