"""add normalized book title

Revision ID: 154f48f3e6bc
Revises: 951617c2b17d
Create Date: 2025-07-12 15:14:47.964422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '154f48f3e6bc'
down_revision: Union[str, None] = '951617c2b17d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('normalized_title', sa.String(), nullable=True))
    op.create_index(op.f('ix_books_normalized_title'), 'books', ['normalized_title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_normalized_title'), table_name='books')
    op.drop_column('books', 'normalized_title')
    # ### end Alembic commands ###
