"""empty message

Revision ID: 776bfc6bf212
Revises: 8938b1bc82db
Create Date: 2025-05-29 12:46:49.822267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '776bfc6bf212'
down_revision: Union[str, None] = '8938b1bc82db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('normalized_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_authors_normalized_name'), 'authors', ['normalized_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_authors_normalized_name'), table_name='authors')
    op.drop_column('authors', 'normalized_name')
    # ### end Alembic commands ###
