"""empty message

Revision ID: ac44af84f8a2
Revises: 1eb4581ecd2e
Create Date: 2025-06-05 18:58:45.815618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac44af84f8a2'
down_revision: Union[str, None] = '1eb4581ecd2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('authors', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('book_authors', 'book_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('book_authors', 'author_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.add_column('books', sa.Column('average_love_rating', sa.Float(), nullable=True))
    op.add_column('books', sa.Column('average_shit_rating', sa.Float(), nullable=True))
    op.add_column('books', sa.Column('sum_of_love_ratings', sa.Float(), nullable=True))
    op.add_column('books', sa.Column('sum_of_shit_ratings', sa.Float(), nullable=True))
    op.alter_column('books', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_column('books', 'sum_of_ratings')
    op.drop_column('books', 'average_rating')
    op.add_column('ratings', sa.Column('love_score', sa.Float(), nullable=True))
    op.add_column('ratings', sa.Column('shit_score', sa.Float(), nullable=True))
    op.alter_column('ratings', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('ratings', 'book_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('ratings', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.drop_column('ratings', 'rating')
    op.alter_column('reviews', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('reviews', 'book_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('reviews', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('reviews', 'rating_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('reviews', 'rating_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('reviews', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('reviews', 'book_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('reviews', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.add_column('ratings', sa.Column('rating', sa.FLOAT(), nullable=True))
    op.alter_column('ratings', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('ratings', 'book_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('ratings', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('ratings', 'shit_score')
    op.drop_column('ratings', 'love_score')
    op.add_column('books', sa.Column('average_rating', sa.FLOAT(), nullable=True))
    op.add_column('books', sa.Column('sum_of_ratings', sa.FLOAT(), nullable=True))
    op.alter_column('books', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('books', 'sum_of_shit_ratings')
    op.drop_column('books', 'sum_of_love_ratings')
    op.drop_column('books', 'average_shit_rating')
    op.drop_column('books', 'average_love_rating')
    op.alter_column('book_authors', 'author_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('book_authors', 'book_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('authors', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    # ### end Alembic commands ###
