"""remove isbn

Revision ID: dbc0439ca2e9
Revises: 154f48f3e6bc
Create Date: 2025-07-12 15:32:15.589852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbc0439ca2e9'
down_revision: Union[str, None] = '154f48f3e6bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_books_isbn', table_name='books')
    op.drop_column('books', 'isbn')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('isbn', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_books_isbn', 'books', ['isbn'], unique=False)
    # ### end Alembic commands ###
